version: '3.1'

services:
  auth:
    build:
      context: /auth
      dockerfile: Dockerfile
    image: auth-sql
    volumes:
      - /controllers:/controllers
    restart: always
    ports:
      - 6000:3000
    depends_on:
      - db
    command: ['npm', 'run', 'dev']

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rajib
      MARIADB_DATABASE: user_auth

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
