####Testing a protected Route
GET http://localhost:3002/posts/recommended
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTA0MzAwMTYsImV4cCI6MTcxMDQzMDYxNiwiYXVkIjoiMSIsImlzcyI6ImxvY2FsaG9zdCJ9.Yohcr3FT5r96n9Qc3CFmOM4c2D0NHLt1UhEBbHidbX0


#### Recent
GET http://localhost:3002/posts/recent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTA0MzAwMTYsImV4cCI6MTcxMDQzMDYxNiwiYXVkIjoiMSIsImlzcyI6ImxvY2FsaG9zdCJ9.Yohcr3FT5r96n9Qc3CFmOM4c2D0NHLt1UhEBbHidbX0

#### Create a Post
POST http://localhost:3002/posts/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTA0MzAwMTYsImV4cCI6MTcxMDQzMDYxNiwiYXVkIjoiMSIsImlzcyI6ImxvY2FsaG9zdCJ9.Yohcr3FT5r96n9Qc3CFmOM4c2D0NHLt1UhEBbHidbX0
Content-Type: application/json

{
  "description": "sadaad",
  "voice": "asdsadad",
  "images": ""
}