####Testing a protected Route
GET http://localhost:3002/posts/recommended
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjA5NjAyODAsImV4cCI6MTcyMTA0NjY4MCwiYXVkIjoiMSIsImlzcyI6ImxvY2FsaG9zdCJ9.at9-Iw49kbSSZcdUzvBJMu0-n09j5Fn8EFtcqtH_FSg


#### Recent
GET http://localhost:3002/posts/recent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjA5NjAyODAsImV4cCI6MTcyMTA0NjY4MCwiYXVkIjoiMSIsImlzcyI6ImxvY2FsaG9zdCJ9.at9-Iw49kbSSZcdUzvBJMu0-n09j5Fn8EFtcqtH_FSg

#### Create a Post
POST http://localhost:3002/posts/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjA5NjAyODAsImV4cCI6MTcyMTA0NjY4MCwiYXVkIjoiMSIsImlzcyI6ImxvY2FsaG9zdCJ9.at9-Iw49kbSSZcdUzvBJMu0-n09j5Fn8EFtcqtH_FSg
Content-Type: application/json

{
  "description": "sadaad",
  "voice": "asdsadad",
  "images": ""
}